### ISSUE TITLE
Individual processing

### ISSUE THREAD

**Issue by ryusaeba** [may0324/DeepCompression-caffe#2]
Hi @may0324 

Thanks for your awesome work. So far, I know the following 
spare_ratio: 0 means disable pruning
quantize_term: false means disable quantization. 
But I saw defalut value for class_num is 256. It seems weight sharing is always perform, right? Could we disable this? 
If I am wrong, please correct me. Thanks :)

**Comment by ryusaeba** [comment]
Oh, It seems class_num is valid when quantize_term is true. Am I correct?

**Comment by may0324** [comment]
@ryusaeba sorry to delete your comment mistakenly.
yes, the class_num is **only valid** when quantize_term is set true

**Comment by ryusaeba** [comment]
Got it! thanks!
